# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: scaler.proto for package 'scaler'

require 'grpc'
require 'scaler_pb'

module Scaler
  module Scaler
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'scaler.Scaler'

      rpc :scale, ::Scaler::ScaleRequest, ::Scaler::ScaleResponse
    end

    Stub = Service.rpc_stub_class
  end
end
